"use client";

import type { ThemeConfig } from "antd";
import type { DefaultTheme } from "styled-components";

import { themeObject } from "./themes/theme-variables";

const remToPixels = (s: string) => parseFloat(s) * 16;

export const getThemeConfig = (theme: DefaultTheme): ThemeConfig => {
  const fontFamily = `${theme.fontFamilies.main}, sans-serif`;
  const borderRadius = remToPixels(theme.borderRadius.xxxs);
  const colorFillAlter = `rgba(${theme.rgb.primary}, 0.05)`;
  const controlOutline = `rgba(${theme.rgb.primary}, 0.2)`;
  const avatarSizeSM = remToPixels(theme.heights.xxs);
  const avatarSize = remToPixels(theme.heights.xs);
  const avatarSizeLG = remToPixels(theme.heights.sm);
  const checkboxSize = remToPixels("1.25");
  const progressLineRadius = remToPixels(theme.borderRadius.xxxxs);
  const menuItemBorderRadius = remToPixels(theme.borderRadius.xxxxs);
  const menuItemPadding = remToPixels(theme.paddings.sm);
  const menuItemHeight = 44;
  const menuIconSize = remToPixels(theme.fontSizes.xl);
  const menuIconGap = 10;
  const collapseContentPadding = `${remToPixels(theme.paddings.xs)}px 0`;

  return {
    token: {
      colorPrimary: theme.primary,
      colorInfo: theme.primary,
      colorSuccess: theme.success,
      colorError: theme.error,
      colorWarning: theme.warning,
      colorPrimaryHover: theme.primary5,
      colorSuccessBg: theme.successBg,
      colorSuccessBorder: theme.successBorder,
      colorFillAlter,
      colorSplit: theme.split,

      colorText: theme.textMain,
      colorTextHeading: theme.heading,
      colorTextDescription: theme.subText,
      colorTextPlaceholder: theme.inputPlaceholder,
      colorTextDisabled: theme.disabled,

      colorBgContainer: theme.background,
      colorBgBase: theme.backgroundColorBase,
      colorBgContainerDisabled: theme.disabledBg,
      colorBgElevated: theme.background,

      colorBorder: theme.borderBase,
      boxShadow: theme.boxShadow,

      controlItemBgHover: theme.itemHoverBg,
      controlOutline,
      controlTmpOutline: controlOutline,
      controlOutlineWidth: 2,
      lineWidthFocus: 0,
      controlInteractiveSize: checkboxSize,

      fontFamily,
      fontFamilyCode: fontFamily,
      fontSize: remToPixels(theme.fontSizes.md),
      fontSizeSM: remToPixels(theme.fontSizes.xs),

      controlHeightSM: remToPixels(theme.heights.sm),
      controlHeight: remToPixels(theme.heights.md),
      controlHeightLG: remToPixels(theme.heights.lg),
      borderRadiusXS: borderRadius,
      borderRadiusSM: borderRadius,
      borderRadius,
      borderRadiusLG: borderRadius,
      borderRadiusOuter: borderRadius,

      wireframe: true,
      screenXSMin: 0,
      screenXS: theme.breakpoints.xs,
      screenXSMax: theme.breakpoints.sm - 1,
      screenSMMin: theme.breakpoints.sm,
      screenSM: theme.breakpoints.sm,
      screenSMMax: theme.breakpoints.md - 1,
      screenMDMin: theme.breakpoints.md,
      screenMD: theme.breakpoints.md,
      screenMDMax: theme.breakpoints.lg - 1,
      screenLGMin: theme.breakpoints.lg,
      screenLG: theme.breakpoints.lg,
      screenLGMax: theme.breakpoints.xl - 1,
      screenXLMin: theme.breakpoints.xl,
      screenXL: theme.breakpoints.xl,
      screenXLMax: theme.breakpoints.xxl - 1,
      screenXXLMin: theme.breakpoints.xxl,
      screenXXL: theme.breakpoints.xxl,
    },
    components: {
      Input: {
        colorTextPlaceholder: theme.inputPlaceholder,
        colorTextDisabled: theme.disabled,
        colorPrimaryHover: theme.primary,
        colorPrimaryActive: theme.primary,
        fontWeightStrong: theme.fontWeights.semibold,
        colorFillAlter,
        activeBorderColor: theme.primary,
        controlOutlineWidth: 0,
      },
      InputNumber: {
        colorPrimaryHover: theme.primary,
        colorPrimaryActive: theme.primary,
        activeBorderColor: theme.primary,
        controlOutlineWidth: 0,
      },
      Select: {
        fontSizeSM: remToPixels(theme.fontSizes.xs),
        colorTextPlaceholder: theme.textSenary,
        colorTextTertiary: theme.icon,
        colorTextQuaternary: theme.textMain,
        colorFillSecondary: theme.backgroundColorBase,
        colorIcon: theme.icon,
        colorIconHover: theme.iconHover,
        colorPrimary: theme.primary,
        colorPrimaryHover: theme.primary,
        controlItemBgActive: theme.primary1,
        controlItemBgHover: theme.itemHoverBg,
      },
      DatePicker: {
        colorIcon: theme.textLight,
        colorTextDisabled: theme.textLight,
        colorPrimary: theme.primary,
        controlItemBgActive: theme.primary1,
        colorTextPlaceholder: theme.inputPlaceholder,
        fontWeightStrong: theme.fontWeights.medium,
        controlHeightSM: remToPixels(theme.heights.xxs),
        controlHeightLG: remToPixels(theme.heights.sm),
        padding: 13,
        paddingXXS: 2,
        hoverBorderColor: theme.primary,

      },
      Form: {
        marginLG: 16,
        colorInfoBorderHover: theme.textBrand,
        labelColor: theme.textMain,
      },
      Checkbox: {
        borderRadiusSM: remToPixels(theme.borderRadius.xxxs),
        colorBorder: theme.borderCheckBox,
        colorPrimary: theme.textBrand,
        colorPrimaryHover: theme.primary,
        colorPrimaryActive: theme.primary,
        colorBgContainer: theme.white,
        colorBgContainerDisabled: theme.borderBase,
        colorTextDisabled: theme.disabled,
        marginXS: 8,
        controlInteractiveSize: 20,
      },
      Radio: {
        radioSize: 20,
        dotSize: 8,
        colorPrimary: theme.textBrand,
        buttonCheckedBg: theme.textBrand,
        controlItemBgActiveDisabled: "#e6e6e6",
      },
      Switch: {
        controlHeight: remToPixels(theme.heights.xs),
        colorPrimary: theme.textBrand,
        colorWhite: theme.background,
        lineHeight: 1.375,
        colorPrimaryBorder: theme.primary1,
        opacityLoading: 0.4,
        colorPrimaryHover: theme.primary,
      },
      Slider: {
        colorPrimaryBorder: theme.primary3,
        colorPrimary: theme.primary4,
        colorPrimaryBorderHover: theme.primary4,
        colorFillSecondary: theme.sliderFillColor,
        colorBorderSecondary: theme.sliderFillColor,
        colorFillContentHover: theme.sliderFillColor,
        colorFillTertiary: theme.backgroundColorBase,
        handleSize: 11,
        handleSizeHover: 11,
        handleLineWidth: 2,
        handleLineWidthHover: 2,
        colorTextDisabled: theme.disabled,
      },
      Upload: {
        colorFillAlter: `rgba(${theme.rgb.primary}, 0.05)`,
        colorPrimaryHover: theme.primary5,
      },

      Layout: {
        controlHeight: 34,
        controlHeightLG: 12.8,
        bodyBg: theme.layoutBodyBg,
        headerBg: theme.layoutSiderBg,
        siderBg: theme.layoutSiderBg,
      },
      Card: {
        colorTextHeading: theme.textMain,
        padding: 20,
        paddingLG: 20,
        boxShadowTertiary: theme.boxShadow,
      },
      Divider: {
        colorSplit: "rgba(0, 0, 0, 0.06)",
      },

      Menu: {
        fontSize: remToPixels(theme.fontSizes.xs),
        colorFillAlter: `rgba(${themeObject["light"].rgb.primary6}, 0.05)`,
        colorBgContainer: "transparent",
        colorText: theme.textSiderSecondary,
        colorSplit: "transparent",
        activeBarWidth: 2,
        activeBarHeight: 0,
        itemHeight: menuItemHeight,
        itemMarginInline: 0,
        itemMarginBlock: 0,
        itemBorderRadius: menuItemBorderRadius,
        subMenuItemBorderRadius: menuItemBorderRadius,
        itemPaddingInline: menuItemPadding,
        iconMarginInlineEnd: menuIconGap,
        iconSize: menuIconSize,
        collapsedIconSize: menuIconSize,
        itemBg: "transparent",
        subMenuItemBg: "transparent",
        itemColor: theme.textQuaternary,
        itemHoverColor: theme.textSiderPrimary,
        itemSelectedColor: theme.textSiderPrimary,
        subMenuItemSelectedColor: theme.textSiderPrimary,
        itemHoverBg: theme.bgBrandSubtle,
        itemActiveBg: theme.bgBrandSubtle,
        itemSelectedBg: theme.bgBrandSubtle,
        horizontalItemBorderRadius: menuItemBorderRadius,
        groupTitleFontSize: remToPixels(theme.fontSizes.xs),
      },
      Pagination: {
        controlItemBgActiveDisabled: "#e6e6e6",
        itemSize: 32,
        itemSizeSM: 24,
        borderRadius: 8,
        colorPrimaryHover: theme.primary,
        colorText: theme.black,
        itemActiveBg: theme.textBrand,
        itemActiveColor: theme.white,
        itemBg: theme.white,
      },
      Breadcrumb: {
        fontSizeIcon: 10,
        colorTextDescription: theme.breadcrumb,
      },
      Tabs: {
        colorPrimaryHover: theme.primary,
        colorPrimary: theme.textBrand,
        colorPrimaryActive: theme.primary,
        colorTextDisabled: theme.disabled,
        colorBorderSecondary: theme.split,
        itemColor: theme.textQuaternary,
        itemHoverColor: theme.textBrand,
        itemActiveColor: theme.textBrand,
        itemSelectedColor: theme.textBrand,
        inkBarColor: theme.textBrand,
        titleFontSize: remToPixels(theme.fontSizes.md),
        horizontalItemPadding: "6px 0",
        horizontalItemGutter: remToPixels(theme.paddings.xs),
      },
      Dropdown: {
        paddingXXS: 0,
        fontSizeIcon: 10,
        controlHeight: 34,
      },
      Tree: {
        controlHeightSM: remToPixels(theme.heights.xxs),
      },

      Table: {
        borderRadius,
        colorBorderSecondary: "#b3cbe1",
        colorTextHeading: theme.textBrand,
        colorFillAlter: `rgba(${theme.rgb.primary}, 0.05)`,
        controlItemBgActive: theme.primary1,
        colorSplit: "rgba(0, 0, 0, 0.15)",
        controlItemBgActiveHover: `rgba(${theme.rgb.primary}, 0.12)`,
      },
      Tag: {
        fontSize: remToPixels(theme.fontSizes.xs),
      },
      Avatar: {
        colorTextPlaceholder: theme.avatarBg,
        colorBorderBg: theme.white,
        containerSizeSM: avatarSizeSM,
        containerSize: avatarSize,
        containerSizeLG: avatarSizeLG,
        textFontSizeSM: remToPixels(theme.fontSizes.xs),
        textFontSize: remToPixels(theme.fontSizes.md),
        textFontSizeLG: remToPixels(theme.fontSizes.lg),
        iconFontSizeSM: remToPixels(theme.fontSizes.sm),
        iconFontSize: remToPixels(theme.fontSizes.lg),
        iconFontSizeLG: remToPixels(theme.fontSizes.xl),
        groupSpace: remToPixels(theme.paddings.xxxs),
        groupOverlapping: remToPixels(theme.paddings.xxxs) / 2,
        groupBorderColor: theme.white,
      },
      Badge: {
        colorPrimary: theme.primary,
        colorTextPlaceholder: "#d9d9d9",
        fontSizeSM: remToPixels(theme.fontSizes.xxs),
      },
      Skeleton: {
        controlHeightXS: 16,
        controlHeightSM: remToPixels(theme.heights.xs),
        controlHeight: remToPixels(theme.heights.md),
        controlHeightLG: remToPixels(theme.heights.lg),
        gradientFromColor: "rgba(190, 190, 190, 0.2)",
      },
      Empty: {
        controlHeightLG: remToPixels(theme.heights.sm),
      },
      Calendar: {
        controlHeightSM: remToPixels(theme.heights.xs) / 1.5,
      },
      Rate: {
        starColor: "#ffc24b",
        colorFillContent: theme.split,
      },

      Alert: {
        colorInfoBg: "#dfefff",
        colorText: theme.black,
        colorTextHeading: theme.black,
        marginSM: 15,
        paddingContentVerticalSM: 8,
        paddingMD: 15,
        paddingContentHorizontalLG: 15,
      },
      Notification: {
        zIndexPopup: 9999,
        width: 384,
        colorSuccess: theme.success,
        colorInfo: theme.info,
        colorWarning: theme.warning,
        colorError: theme.error,
        colorInfoBg: theme.notification.info,
        colorSuccessBg: theme.notification.success,
        colorWarningBg: theme.notification.warning,
        colorErrorBg: theme.notification.error,
        colorIconHover: "rgba(0, 0, 0, 0.67)",
        fontSizeLG: remToPixels(theme.fontSizes.lg),
        boxShadow: theme.modalBoxShadow,
      },
      Modal: {
        colorTextDescription: theme.icon,
        colorIcon: theme.icon,
        boxShadow: theme.modalBoxShadow,
        lineHeight: 1.57,
      },
      Popconfirm: {
        fontWeightStrong: theme.fontWeights.semibold,
        colorPrimary: theme.primary,
      },
      Popover: {
        zIndexPopup: 2000,
        controlHeight: 34,
        sizePopupArrow: 20,
      },
      Progress: {
        marginXS: 12,
        colorFillSecondary: theme.backgroundColorBase,
        defaultColor: theme.textBrand,
        remainingColor: theme.gray200,
        circleTextColor: theme.textMain,
        lineBorderRadius: progressLineRadius,
        colorText: theme.textTertiary,
        fontSize: remToPixels(theme.fontSizes.xs),
      },
      Result: {
        fontSizeHeading3: remToPixels(theme.fontSizes.xxl),
        lineHeightHeading3: 1.8,
      },
      Spin: {
        controlHeight: remToPixels(theme.heights.xs),
        controlHeightLG: remToPixels(theme.heights.sm),
        colorPrimary: theme.primary,
      },
      Steps: {
        iconSize: remToPixels(theme.heights.xs),
        iconFontSize: remToPixels(theme.fontSizes.lg),
        controlHeight: remToPixels(theme.heights.md),
        controlHeightSM: remToPixels(theme.heights.xxs),
        fontSizeHeading3: remToPixels(theme.fontSizes.xxl),
        colorPrimary: theme.primary,
      },
      Button: {
        colorPrimary: theme.textBrand,
        colorPrimaryHover: theme.primary,
        colorPrimaryActive: theme.primary,
        colorLinkHover: theme.textBrand,
        colorLinkActive: theme.primary,
        controlOutlineWidth: 0,
        fontSizeSM: remToPixels(theme.fontSizes.md),
        fontSize: remToPixels(theme.fontSizes.md),
        fontSizeLG: remToPixels(theme.fontSizes.lg),
        fontWeight: theme.fontWeights.medium,
        lineHeight: 1.5,
        paddingInline: remToPixels(theme.paddings.xs),
        paddingInlineSM: remToPixels(theme.paddings.xs),
        colorTextDisabled: theme.textSenary,
        colorBgContainerDisabled: theme.tertiaryBg,
        boxShadow: "none",
        boxShadowSecondary: "none",
        colorBgTextHover: theme.bgBrandSubtle,
        colorBgTextActive: theme.bgBrandSubtle,
        colorError: theme.error,
        colorErrorHover: theme.error,
        colorErrorActive: theme.error,
      },
      Collapse: {
        headerBg: "transparent",
        contentBg: "transparent",
        borderlessContentBg: "transparent",
        borderlessContentPadding: collapseContentPadding,
        contentPadding: collapseContentPadding,
        colorTextHeading: theme.textMain,
        fontWeightStrong: theme.fontWeights.semibold,
        fontSize: remToPixels(theme.fontSizes.xs),
        fontSizeLG: remToPixels(theme.fontSizes.md),
        colorTextDisabled: theme.disabled,
        colorBorder: theme.border,
      },
      Tooltip: {
        colorBgSpotlight: theme.textTertiary,
        fontSize: remToPixels(theme.fontSizes.xxs),
      },
      Segmented: {
        itemSelectedBg: theme.textBrand,
        itemColor: theme.black,
        itemSelectedColor: theme.white,
        trackBg: theme.primary1,
        itemHoverBg: theme.primary2,
        itemActiveBg: theme.primary3,
      }
    },
  };
};
